modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/WonderfulEnchantmentsMod/issues"

[[mods]]
    modId="wonderful_enchantments"
    version="1.5.1-unfinished"
    displayName="Wonderful Enchantments"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/WonderfulEnchantmentsMod/1.17.1/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"
    logoFile="logo.png"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Mod adding a lot of new unique enchantments to the game.'''

[[dependencies.wonderful_enchantments]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wonderful_enchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wonderful_enchantments]]
    modId="majrusz_library"
    mandatory=true
    versionRange="[2.4.0,3.0.0)"
    ordering="NONE"
    side="BOTH"