modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsEnchantmentsMod/issues"

[[mods]]
    modId="majruszsenchantments"
    version="1.7.7-unfinished"
    displayName="Majrusz's Enchantments"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsEnchantmentsMod/1.19.X/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"
    logoFile="logo.png"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''Mod that adds plenty of unique and balanced enchantments to the game.'''

[[dependencies.majruszsenchantments]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsenchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsenchantments]]
    modId="mlib"
    mandatory=true
    versionRange="[3.0.0,4.0.0)"
    ordering="NONE"
    side="BOTH"