modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsEnchantmentsMod/issues"

[[mods]]
    modId="majruszsenchantments"
    version="1.7.1"
    displayName="Majrusz's Enchantments"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszsEnchantmentsMod/1.19/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"
    logoFile="logo.png"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''adds plenty of unique and balanced enchantments to the game.'''

[[dependencies.majruszsenchantments]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsenchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsenchantments]]
    modId="majruszlib"
    mandatory=true
    versionRange="[2.12.1,3.0.0)"
    ordering="NONE"
    side="BOTH"