modLoader="javafml"

loaderVersion="[34,)"

license="All rights reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"

[[mods]]

modId="wonderful_enchantments"

version="1.16.3-0.8.1"

displayName="Wonderful Enchantments"

updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"

displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"

logoFile="logo.png"

credits="Thanks for all your support!"

authors="Majrusz"

description='''
Mod adding a lot of new unique enchantments to the game.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"