modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"

[[mods]]

modId="wonderful_enchantments"

version="1.15.2-0.2.0"

displayName="Wonderful Enchantments"

updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"

displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments"

logoFile="logo.png" #optional

credits="Thanks for all your suport!"

authors="Majrusz" #optional

description='''
Mod adding a lot of new unique enchantments to the game.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
